"use client";

import { api } from "@/lib/api";
import { AiModule, ApiResponse, Camera } from "@/types";
import {
  Check,
  ChevronLeft,
  ChevronRight,
  Globe,
  HardDrive,
  Loader2,
  Network,
  Radio,
  X,
} from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

/**
 * Simple camera wizard. The user picks a source TYPE and fills a few friendly
 * fields — never an `ffmpeg:device?…` string, a go2rtc host or a stream name.
 * Internal stream names are generated by the backend (`cam_<uuid>`).
 *
 * Create  -> POST /api/cameras/provision  (validate -> go2rtc -> verify -> save -> modules)
 * Edit    -> PUT  /api/cameras/:id        (source changes update the same stream)
 */

type SourceType = "rtsp" | "webcam" | "go2rtc" | "nvr" | "keep";

const RESOLUTIONS = ["640x480", "1280x720", "1920x1080"];
const FPS_OPTIONS = [15, 20, 25, 30];

interface Props {
  camera?: Camera | null;
  onClose: () => void;
  onSuccess: () => void;
}

interface Go2rtcStream {
  name: string;
  sources: string[];
}

export function CameraFormDialog({ camera, onClose, onSuccess }: Props) {
  const { t } = useTranslation();
  const isEdit = Boolean(camera);

  const [step, setStep] = useState(0);
  const [name, setName] = useState(camera?.name ?? "");
  const [location, setLocation] = useState(camera?.location ?? "");
  const [sourceType, setSourceType] = useState<SourceType>(isEdit ? "keep" : "rtsp");

  const [rtspUrl, setRtspUrl] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [device, setDevice] = useState("");
  const [resolution, setResolution] = useState("1280x720");
  const [fps, setFps] = useState(30);
  const [streamName, setStreamName] = useState("");

  const [devices, setDevices] = useState<string[]>([]);
  const [streams, setStreams] = useState<Go2rtcStream[]>([]);
  const [modules, setModules] = useState<AiModule[]>([]);
  const [selected, setSelected] = useState<string[]>(
    camera?.cameraModules?.filter((m) => m.isEnabled).map((m) => m.module.code) ?? [],
  );

  const [busy, setBusy] = useState(false);
  const [testing, setTesting] = useState(false);
  const [testResult, setTestResult] = useState<{ ok: boolean; message: string } | null>(null);
  const [error, setError] = useState("");

  const loadModules = useCallback(async () => {
    try {
      const res = await api.get<ApiResponse<AiModule[]>>("/modules");
      if (res.success) setModules(res.data);
    } catch {
      /* non-fatal */
    }
  }, []);

  const loadDevices = useCallback(async () => {
    try {
      const res = await api.get<ApiResponse<{ devices: string[] }>>("/go2rtc/devices");
      if (res.success) {
        setDevices(res.data.devices);
        setDevice((prev) => prev || res.data.devices[0] || "");
      }
    } catch {
      setDevices([]);
    }
  }, []);

  const loadStreams = useCallback(async () => {
    try {
      const res = await api.get<ApiResponse<Go2rtcStream[]>>("/go2rtc/streams");
      if (res.success) {
        setStreams(res.data);
        setStreamName((prev) => prev || res.data[0]?.name || "");
      }
    } catch {
      setStreams([]);
    }
  }, []);

  useEffect(() => {
    void loadModules();
  }, [loadModules]);

  useEffect(() => {
    if (step !== 1) return;
    if (sourceType === "webcam") void loadDevices();
    if (sourceType === "go2rtc") void loadStreams();
  }, [step, sourceType, loadDevices, loadStreams]);

  const sourcePayload = () => {
    if (sourceType === "keep") return {};
    return {
      sourceType,
      rtspUrl: sourceType === "rtsp" || sourceType === "nvr" ? rtspUrl : undefined,
      username: username || undefined,
      password: password || undefined,
      device: sourceType === "webcam" ? device : undefined,
      resolution: sourceType === "webcam" ? resolution : undefined,
      fps: sourceType === "webcam" ? fps : undefined,
      streamName: sourceType === "go2rtc" ? streamName : undefined,
    };
  };

  const testConnection = async () => {
    setTesting(true);
    setTestResult(null);
    try {
      const res = await api.post<{ success: boolean; message?: string }>("/go2rtc/test", sourcePayload());
      setTestResult({ ok: Boolean(res.success), message: res.message ?? "" });
    } catch (err) {
      setTestResult({ ok: false, message: (err as Error).message });
    } finally {
      setTesting(false);
    }
  };

  const canNext = step === 0 ? name.trim().length > 0 && location.trim().length > 0 : true;

  const submit = async () => {
    setBusy(true);
    setError("");
    try {
      if (isEdit && camera) {
        await api.put(`/cameras/${camera.id}`, { name, location, ...sourcePayload() });
      } else {
        await api.post("/cameras/provision", {
          name,
          location,
          modules: selected,
          ...sourcePayload(),
        });
      }
      onSuccess();
    } catch (err) {
      setError((err as Error).message || t("cameraWizard.failed"));
    } finally {
      setBusy(false);
    }
  };

  const sourceOptions: { id: SourceType; label: string; hint: string; icon: React.ReactNode }[] = [
    { id: "rtsp", label: t("cameraWizard.srcRtsp"), hint: t("cameraWizard.srcRtspHint"), icon: <Network className="w-4 h-4" /> },
    { id: "webcam", label: t("cameraWizard.srcWebcam"), hint: t("cameraWizard.srcWebcamHint"), icon: <HardDrive className="w-4 h-4" /> },
    { id: "go2rtc", label: t("cameraWizard.srcExisting"), hint: t("cameraWizard.srcExistingHint"), icon: <Radio className="w-4 h-4" /> },
    { id: "nvr", label: t("cameraWizard.srcNvr"), hint: t("cameraWizard.srcNvrHint"), icon: <Globe className="w-4 h-4" /> },
  ];
  if (isEdit) {
    sourceOptions.unshift({
      id: "keep", label: t("cameraWizard.srcKeep"), hint: t("cameraWizard.srcKeepHint"), icon: <Check className="w-4 h-4" />,
    });
  }

  const inputCls =
    "w-full bg-neutral-950 border border-neutral-800 rounded-lg px-3 py-2 text-sm text-neutral-100 focus:border-blue-600 focus:outline-none";

  return (
    <div className="fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div
        className="bg-neutral-900 border border-neutral-800 rounded-2xl w-full max-w-xl shadow-2xl max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-neutral-800 sticky top-0 bg-neutral-900 z-10">
          <div>
            <h2 className="text-base font-semibold text-neutral-100">
              {isEdit ? t("cameraWizard.editTitle") : t("cameraWizard.addTitle")}
            </h2>
            <div className="flex items-center gap-1.5 mt-1.5">
              {[0, 1, 2].map((i) => (
                <span
                  key={i}
                  className={`h-1.5 rounded-full transition-all ${
                    i === step ? "w-6 bg-blue-500" : i < step ? "w-3 bg-blue-800" : "w-3 bg-neutral-800"
                  }`}
                />
              ))}
              <span className="text-[11px] text-neutral-500 ml-1">
                {t(`cameraWizard.step${step + 1}`)}
              </span>
            </div>
          </div>
          <button onClick={onClose} className="text-neutral-400 hover:text-white transition">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-5 space-y-4">
          {/* Step 1 — basics */}
          {step === 0 && (
            <>
              <div>
                <label className="block text-xs text-neutral-400 mb-1">{t("cameraWizard.name")}</label>
                <input className={inputCls} value={name} onChange={(e) => setName(e.target.value)} placeholder="Gate Camera" />
              </div>
              <div>
                <label className="block text-xs text-neutral-400 mb-1">{t("cameraWizard.location")}</label>
                <input className={inputCls} value={location} onChange={(e) => setLocation(e.target.value)} placeholder="Main Entrance" />
              </div>
            </>
          )}

          {/* Step 2 — source */}
          {step === 1 && (
            <>
              <div className="grid grid-cols-2 gap-2">
                {sourceOptions.map((opt) => (
                  <button
                    key={opt.id}
                    type="button"
                    onClick={() => { setSourceType(opt.id); setTestResult(null); }}
                    className={`text-left p-3 rounded-xl border transition ${
                      sourceType === opt.id
                        ? "border-blue-600 bg-blue-950/30"
                        : "border-neutral-800 hover:border-neutral-700"
                    }`}
                  >
                    <div className="flex items-center gap-2 text-neutral-200 text-sm font-medium">
                      {opt.icon}
                      {opt.label}
                    </div>
                    <p className="text-[11px] text-neutral-500 mt-1">{opt.hint}</p>
                  </button>
                ))}
              </div>

              {(sourceType === "rtsp" || sourceType === "nvr") && (
                <div className="space-y-3">
                  <div>
                    <label className="block text-xs text-neutral-400 mb-1">{t("cameraWizard.rtspUrl")}</label>
                    <input className={inputCls} value={rtspUrl} onChange={(e) => setRtspUrl(e.target.value)}
                      placeholder="rtsp://192.168.1.10:554/Streaming/Channels/101" />
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <input className={inputCls} value={username} onChange={(e) => setUsername(e.target.value)}
                      placeholder={t("cameraWizard.username")} />
                    <input className={inputCls} type="password" value={password} onChange={(e) => setPassword(e.target.value)}
                      placeholder={t("cameraWizard.password")} />
                  </div>
                </div>
              )}

              {sourceType === "webcam" && (
                <div className="space-y-3">
                  <div>
                    <label className="block text-xs text-neutral-400 mb-1">{t("cameraWizard.device")}</label>
                    <select className={inputCls} value={device} onChange={(e) => setDevice(e.target.value)}>
                      {devices.length === 0 && <option value="">{t("cameraWizard.noDevices")}</option>}
                      {devices.map((d) => <option key={d} value={d}>{d}</option>)}
                    </select>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <select className={inputCls} value={resolution} onChange={(e) => setResolution(e.target.value)}>
                      {RESOLUTIONS.map((r) => <option key={r} value={r}>{r}</option>)}
                    </select>
                    <select className={inputCls} value={fps} onChange={(e) => setFps(Number(e.target.value))}>
                      {FPS_OPTIONS.map((f) => <option key={f} value={f}>{f} FPS</option>)}
                    </select>
                  </div>
                  <p className="text-[11px] text-neutral-500">{t("cameraWizard.webcamNote")}</p>
                </div>
              )}

              {sourceType === "go2rtc" && (
                <div>
                  <label className="block text-xs text-neutral-400 mb-1">{t("cameraWizard.existingStream")}</label>
                  <select className={inputCls} value={streamName} onChange={(e) => setStreamName(e.target.value)}>
                    {streams.length === 0 && <option value="">{t("cameraWizard.noStreams")}</option>}
                    {streams.map((s) => <option key={s.name} value={s.name}>{s.name}</option>)}
                  </select>
                </div>
              )}

              {sourceType !== "keep" && (
                <div className="flex items-center gap-3">
                  <button
                    type="button"
                    onClick={testConnection}
                    disabled={testing}
                    className="px-3 py-2 text-xs rounded-lg border border-neutral-700 text-neutral-200 hover:bg-neutral-800 transition flex items-center gap-2 disabled:opacity-50"
                  >
                    {testing && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
                    {t("cameraWizard.testConnection")}
                  </button>
                  {testResult && (
                    <span className={`text-xs ${testResult.ok ? "text-emerald-400" : "text-red-400"}`}>
                      {testResult.ok ? t("cameraWizard.testOk") : testResult.message || t("cameraWizard.testFail")}
                    </span>
                  )}
                </div>
              )}
            </>
          )}

          {/* Step 3 — modules */}
          {step === 2 && (
            <>
              <p className="text-xs text-neutral-400">{t("cameraWizard.modulesHint")}</p>
              <div className="space-y-2">
                {modules.map((m) => {
                  const checked = selected.includes(m.code);
                  return (
                    <label
                      key={m.id}
                      className={`flex items-start gap-3 p-3 rounded-xl border cursor-pointer transition ${
                        checked ? "border-blue-600 bg-blue-950/30" : "border-neutral-800 hover:border-neutral-700"
                      }`}
                    >
                      <input
                        type="checkbox"
                        className="mt-0.5 accent-blue-600"
                        checked={checked}
                        onChange={() =>
                          setSelected((prev) =>
                            prev.includes(m.code) ? prev.filter((c) => c !== m.code) : [...prev, m.code],
                          )
                        }
                      />
                      <div className="min-w-0">
                        <p className="text-sm text-neutral-200">{m.name}</p>
                        {m.description && <p className="text-[11px] text-neutral-500">{m.description}</p>}
                      </div>
                    </label>
                  );
                })}
              </div>
              {selected.includes("INTRUSION") && (
                <p className="text-[11px] text-blue-400">{t("cameraWizard.roiHint")}</p>
              )}
            </>
          )}

          {error && (
            <div className="bg-red-950/40 border border-red-900 text-red-300 text-xs rounded-lg p-3">{error}</div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-5 border-t border-neutral-800">
          <button
            type="button"
            onClick={() => (step === 0 ? onClose() : setStep((s) => s - 1))}
            className="px-3 py-2 text-xs rounded-lg border border-neutral-800 text-neutral-300 hover:bg-neutral-800 transition flex items-center gap-1"
          >
            <ChevronLeft className="w-3.5 h-3.5" />
            {step === 0 ? t("common.cancel") : t("common.previous")}
          </button>

          {step < 2 ? (
            <button
              type="button"
              disabled={!canNext}
              onClick={() => setStep((s) => s + 1)}
              className="px-4 py-2 text-xs rounded-lg bg-blue-600 hover:bg-blue-500 text-white transition flex items-center gap-1 disabled:opacity-40"
            >
              {t("common.next")}
              <ChevronRight className="w-3.5 h-3.5" />
            </button>
          ) : (
            <button
              type="button"
              disabled={busy}
              onClick={submit}
              className="px-4 py-2 text-xs rounded-lg bg-blue-600 hover:bg-blue-500 text-white transition flex items-center gap-2 disabled:opacity-50"
            >
              {busy && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
              {isEdit ? t("common.save") : t("cameraWizard.create")}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
